### ISSUE TITLE
Hourly Forecasts

### ISSUE THREAD

**Issue by wrussell1999** [MLH-Fellowship/prep-project-4.1.4#1]
Allow the user to put a time + date in to get an idea of what the weather will be like then. At the moment, it only displays the weather right now.

**Comment by DinuBotan** [comment]
Hey @NoahCardoza, if nobody else wants this issue, could you please assign it to me and @shravani05?

**Comment by DinuBotan** [comment]
Btw, I checked the API and it requires a pro subscription to get hourly data, however it is possible to get every 3 hours forecast for the following 5 days with a free subscription.

**Comment by DinuBotan** [comment]
Btw, I checked the API and it requires a pro subscription to get the hourly forecast. However, we can get the forecast for every 3 hours for the following 5 days with the free subscription. I think we could work with that.

**Comment by NoahCardoza** [comment]
Good catch, I think you are right!
