### ISSUE TITLE
Pick title and update logo favicon

### ISSUE THREAD

**Issue by NoahCardoza** [MLH-Fellowship/prep-project-4.1.4#18]
Sooner or later we are going to have to come up with a neat name and add a custom favicon.

Any suggestions?

**Comment by Sargam-Agarwal** [comment]
Weatheromatic
Weather Muxotic / Weather Musiotic /Weather Muxiotic

**Comment by Sargam-Agarwal** [comment]
As for logo, we need to create one or we can use, lets say, some related cartoon image on google!? @NoahCardoza

**Comment by Pratyush1606** [comment]
@NoahCardoza I think this issue needs to be closed before #12 because for making PWA, it requires a favicon of a specific size.

**Comment by NoahCardoza** [comment]
@Sargam-Agarwal we can either create one or pull one off Google, I think both are good ideas.

@Pratyush1606 It might be a good idea to link this issue to #19.

**Comment by NoahCardoza** [comment]
Name: Sound Forecast

![image](https://user-images.githubusercontent.com/10343470/142643890-40a7caa8-a395-41ef-8ccb-10e6a759374a.png)

**Comment by Pratyush1606** [comment]
@NoahCardoza Should we change the heading on the first page from `MLH Prep` to `SOUND FORECAST` with the corresponding icon?
