### ISSUE TITLE
API having trouble resolving cities

### ISSUE THREAD

**Issue by NoahCardoza** [MLH-Fellowship/prep-project-4.1.4#21]
Here are a couple of examples:

![image (2)](https://user-images.githubusercontent.com/10343470/142647075-bd85f4fa-d2fa-4f2e-8c94-757655ff643b.png)

![image (1)](https://user-images.githubusercontent.com/10343470/142647082-8eefe810-d3b9-47cc-8e9d-cc9ae12b1b35.png)

![image](https://user-images.githubusercontent.com/10343470/142647086-0f7367e0-ed2f-416b-aab3-8cd9bcb1abd7.png)

You can see that the city found doesn't match the city searched in any of the cases. I'm not entirely sure why but can someone look into it?

**Comment by DinuBotan** [comment]
It looks like there's something wrong with the API. I wasn't able to get it working when making requests based on City Name, State, and Country, although it should based on the documentation.
A workaround is to make API requests based on a city's latitude and longitude.

**Comment by NoahCardoza** [comment]
Good idea!
