### ISSUE TITLE
Move weather picture from card to background

### ISSUE THREAD

**Issue by helenduz** [MLH-Fellowship/prep-project-4.1.4#26]
Instead of putting the weather picture inside a card, we can probably display it in the background.

**Comment by helenduz** [comment]
This seems like it would be a big UI change - @NoahCardoza would it be okay? If so, can you assign @Bhavika-Gianey and me to this issue?

**Comment by NoahCardoza** [comment]
Sounds like a good idea!

**Comment by NoahCardoza** [comment]
How is this coming along?
