### ISSUE TITLE
Using Geolocation API to get the users location

### ISSUE THREAD

**Issue by wrussell1999** [MLH-Fellowship/prep-project-4.1.4#3]
Using the Geolocation API to get the users location as the first weather results displayed, instead of just New York City.

Read more [here](https://developer.mozilla.org/en-US/docs/Web/API/Geolocation_API).

**Comment by shravani05** [comment]
@NoahCardoza can you please assign me and @DinuBotan this issue?

**Comment by Pratyush1606** [comment]
@NoahCardoza can you please assign this to me and @rajat2502, I have not worked so much on APIs and Javascript fetch APIs, so it would be a good learning experience.

**Comment by NoahCardoza** [comment]
@Pratyush1606 It seems @shravani05 asked for the issue first. Unless she is fine giving it up I'll be assigning it to her and @DinuBotan for the time being.

Sorry for the mixup!
