### ISSUE TITLE
Remove unnecessary and unused react artifacts from code base

### ISSUE THREAD

**Issue by obasekiosa** [MLH-Fellowship/prep-project-4.1.4#38]
Some artefacts are imported from the react library but are not used.
It would be nice to remove them and clean up the codebase.
This would make the code base cleaner.

![dev-error](https://user-images.githubusercontent.com/12957252/143224679-7a58540e-10af-4b41-a61f-024acff6b496.JPG)

**Comment by obasekiosa** [comment]
@NoahCardoza 
Could you please assign this to me and @EkjotKaur

**Comment by NoahCardoza** [comment]
Good catch!
