### ISSUE TITLE
Render the UI of the tracks fetched using Spotify API

### ISSUE THREAD

**Issue by Sargam-Agarwal** [MLH-Fellowship/prep-project-4.1.4#41]
Currently, the UI is just a simple ListView like shown below 👇🏻 
![Screenshot (6)](https://user-images.githubusercontent.com/72149858/143388180-36f8ab8f-aa73-412e-85af-ed5ddadb1f8f.png)
There is a lot of scope of improvement here, like working on the font style, the cover image displayed, etc.

**Comment by Sargam-Agarwal** [comment]
@DinuBotan you might want to take a look at this 😃

**Comment by DinuBotan** [comment]
Sure I'll work on this. @NoahCardoza please assign this to me and @shravani05

**Comment by NoahCardoza** [comment]
@DinuBotan make sure to look into those squashed images! I left some comments about how to fix them in @Sargam-Agarwal initial PR. We decided to break it into a new issue to make more available issues.

**Comment by Sargam-Agarwal** [comment]
https://github.com/MLH-Fellowship/prep-project-4.1.4/pull/27#discussion_r756284846

Here is the direct link of what exactly Noah is talking about 👍
@DinuBotan @shravani05
